### ISSUE TITLE
Setting plugin timeout

### ISSUE THREAD

**Issue by nemski** [scoutapp/scout-client#30]
As of Scout client 4.0.0, custom timeouts for a plugin are supported, but there's no documentation on how to implement this from within a plugin. I've tried the following global variable in my plugin:

```ruby
class NameResolver < Scout::Plugin
  TIMEOUT=77
```

but running scout test shows this is not taking affect:

```sh
10:35 $ time bundle exec scout test name_resolution/name_resolver.rb nameserver=8.8.8.7
...
== Output:
{:reports=>[],
 :alerts=>[],
 :errors=>
  [{:plugin_id=>nil,
    :created_at=>"2015-08-05 00:36:24",
    :fields=>
     {:subject=>"Plugin took too long to run",
      :body=>"Execution timed out."}}],
 :summaries=>[],
 :snapshot=>""}

real	1m0.431s
user	0m0.301s
sys	0m0.087s
```

**Comment by itsderek23** [comment]
Hi @nemski,

This timeout functionality was used by a couple of plugins we created that could take a while to run parsing large log files. 

Since this was added, we've largely dropped those plugins in favor of using [StatsD](https://scoutapp.com/statsd) to collect event information as this is far more efficient.

The problem w/large timeouts is plugins run synchronously. If one plugin takes a long time to run, it's possible no data will be reported for other plugins. 

If you need to collect data that takes a while to generate, we suggest generating that data through a background job or Cron job, dumping a file w/metrics in JSON format somewhere, and having a plugin report data from the file.
